In [6]:
import numpy as np
import pandas as pd
import scipy
from sklearn.linear_model import LinearRegression

In [2]:
df = pd.read_csv('test_dataset.csv', header=0)

In [3]:
df.head(5)

   temperature  humidity  brightness  rip  noise  airquality
0           20        70          52    0     55           5
1           28        75          67    1     33           6
2           25        72          68    1     52           6
3           20        76          63    1     64           8
4           26        70          69    1     45           3

In [5]:
df.corr()

             temperature  humidity  brightness       rip     noise  airquality
temperature     1.000000 -0.047036    0.213672 -0.153285 -0.003832   -0.076414
humidity       -0.047036  1.000000   -0.052593  0.105354 -0.029725   -0.042104
brightness      0.213672 -0.052593    1.000000  0.067252 -0.137472   -0.071420
rip            -0.153285  0.105354    0.067252  1.000000  0.028910    0.070230
noise          -0.003832 -0.029725   -0.137472  0.028910  1.000000    0.017957
airquality     -0.076414 -0.042104   -0.071420  0.070230  0.017957    1.000000